# If you get a ton of errors, use this to convert your legacy window rules to
# the new format: https://itsohen.github.io/hyprrulefix/

windowrule = float on, size 622 652, stay_focused on, match:class (clipse)
windowrule = float on, size 800 600, center on, match:class ^(Calcure)$
windowrule = float on, center on, size 1050 600, match:class (Omarchy)
windowrule = tile on, match:class (TilingOmarchy)
windowrule = float on, center on, size 800 800, match:class (Impala)
